on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build --tag ghcr.io/$GITHUB_ACTOR/cham:latest \
          --tag ghcr.io/$GITHUB_ACTOR/cham:$(echo $GITHUB_SHA | head -c7) \
          .
      - name: Push Docker image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/cham:latest
          docker push ghcr.io/$GITHUB_ACTOR/cham:$(echo $GITHUB_SHA | head -c7)
